[package]
name = "deduplicator"
version = "0.1.0"
authors = ["Aj0SK <andrejkorman@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
walkdir = "2"
queue = "0.3.0"
wyhash = "0.2.0"
md5 = "0.7.0"
